Metrics/AbcSize:      # Отключение ABC-проверок
  Enabled: false
Layout/LineLength:    # Длина строк 80
  Max: 80
Metrics/MethodLength: # Количество строк кода 15
  Max: 15
Style/NegatedIf:      # Не форсировать unless
  Enabled: false
AllCops:              # Автоматически включать все проверки
  NewCops: enable
